class Solution {
public:
    string intToRoman(int num) {
        map<int,string> mp;
        mp[1]="I";
        mp[5]="V";
        mp[10]="X";
        mp[50]="L";
        mp[100]="C";
        mp[500]="D";
        mp[1000]="M";
        mp[4]="IV";
        mp[9]="IX";
        mp[40]="XL";
        mp[90]="XC";
        mp[400]="CD";
        mp[900]="CM";
        string s="";
        while(num!=0)
        {
            if(num>=1000)
            {
                s+=mp[1000];
                num-=1000;
            }
            else
            if(num>=900)
            {
                s+=mp[900];
                num-=900;
            }
            else
            if(num>=500)
            {
                s+=mp[500];
                num-=500;
            }
            else
            if(num>=400)
            {
                s+=mp[400];
                num-=400;
            }
            else
            if(num>=100)
            {
                s+=mp[100];
                num-=100;
            }
            else
            if(num>=90)
            {
                s+=mp[90];
                num-=90;
            }
            else
            if(num>=50)
            {
                s+=mp[50];
                num-=50;
            }
            else
            if(num>=40)
            {
                s+=mp[40];
                num-=40;
            }
            else
            if(num>=10)
            {
                s+=mp[10];
                num-=10;
            }
            else
            if(num>=9)
            {
                s+=mp[9];
                num-=9;
            }
            else
            if(num>=5)
            {
                s+=mp[5];
                num-=5;
            }
            else
            if(num>=4)
            {
                s+=mp[4];
                num-=4;
            }
            else
            {
                s+=mp[1];
                num-=1;
            }
        }
        return s;
    }
};
